/**
 * Comprehensive list of 189 languages supported by Google Cloud Speech-to-Text API
 * Used for multilingual voice search in the Emilist platform
 */
export const supportedLanguages = [
  { code: 'af-ZA', name: 'Afrikaans' },
  { code: 'am-ET', name: 'Amharic' },
  { code: 'ar-DZ', name: 'Arabic (Algeria)' },
  { code: 'ar-BH', name: 'Arabic (Bahrain)' },
  { code: 'ar-EG', name: 'Arabic (Egypt)' },
  { code: 'ar-IQ', name: 'Arabic (Iraq)' },
  { code: 'ar-JO', name: 'Arabic (Jordan)' },
  { code: 'ar-KW', name: 'Arabic (Kuwait)' },
  { code: 'ar-LB', name: 'Arabic (Lebanon)' },
  { code: 'ar-MA', name: 'Arabic (Morocco)' },
  { code: 'ar-OM', name: 'Arabic (Oman)' },
  { code: 'ar-QA', name: 'Arabic (Qatar)' },
  { code: 'ar-SA', name: 'Arabic (Saudi Arabia)' },
  { code: 'ar-PS', name: 'Arabic (State of Palestine)' },
  { code: 'ar-TN', name: 'Arabic (Tunisia)' },
  { code: 'ar-AE', name: 'Arabic (United Arab Emirates)' },
  { code: 'ar-YE', name: 'Arabic (Yemen)' },
  { code: 'hy-AM', name: 'Armenian' },
  { code: 'az-AZ', name: 'Azerbaijani' },
  { code: 'eu-ES', name: 'Basque' },
  { code: 'bn-BD', name: 'Bengali (Bangladesh)' },
  { code: 'bn-IN', name: 'Bengali (India)' },
  { code: 'bs-BA', name: 'Bosnian' },
  { code: 'bg-BG', name: 'Bulgarian' },
  { code: 'my-MM', name: 'Burmese' },
  { code: 'ca-ES', name: 'Catalan' },
  { code: 'yue-Hant-HK', name: 'Chinese, Cantonese (Traditional Hong Kong)' },
  { code: 'zh-Hans-CN', name: 'Chinese, Mandarin (Simplified, China)' },
  { code: 'zh-Hant-TW', name: 'Chinese, Mandarin (Traditional, Taiwan)' },
  { code: 'zh-Hant-HK', name: 'Chinese (Traditional, Hong Kong)' },
  { code: 'hr-HR', name: 'Croatian' },
  { code: 'cs-CZ', name: 'Czech' },
  { code: 'da-DK', name: 'Danish' },
  { code: 'nl-BE', name: 'Dutch (Belgium)' },
  { code: 'nl-NL', name: 'Dutch (Netherlands)' },
  { code: 'en-AU', name: 'English (Australia)' },
  { code: 'en-CA', name: 'English (Canada)' },
  { code: 'en-GH', name: 'English (Ghana)' },
  { code: 'en-HK', name: 'English (Hong Kong)' },
  { code: 'en-IN', name: 'English (India)' },
  { code: 'en-IE', name: 'English (Ireland)' },
  { code: 'en-KE', name: 'English (Kenya)' },
  { code: 'en-NZ', name: 'English (New Zealand)' },
  { code: 'en-NG', name: 'English (Nigeria)' },
  { code: 'en-PK', name: 'English (Pakistan)' },
  { code: 'en-PH', name: 'English (Philippines)' },
  { code: 'en-SG', name: 'English (Singapore)' },
  { code: 'en-ZA', name: 'English (South Africa)' },
  { code: 'en-TZ', name: 'English (Tanzania)' },
  { code: 'en-GB', name: 'English (United Kingdom)' },
  { code: 'en-US', name: 'English (United States)' },
  { code: 'et-EE', name: 'Estonian' },
  { code: 'fil-PH', name: 'Filipino' },
  { code: 'fi-FI', name: 'Finnish' },
  { code: 'fr-BE', name: 'French (Belgium)' },
  { code: 'fr-CA', name: 'French (Canada)' },
  { code: 'fr-FR', name: 'French (France)' },
  { code: 'fr-CH', name: 'French (Switzerland)' },
  { code: 'gl-ES', name: 'Galician' },
  { code: 'ka-GE', name: 'Georgian' },
  { code: 'de-AT', name: 'German (Austria)' },
  { code: 'de-DE', name: 'German (Germany)' },
  { code: 'de-CH', name: 'German (Switzerland)' },
  { code: 'el-GR', name: 'Greek' },
  { code: 'gu-IN', name: 'Gujarati' },
  { code: 'iw-IL', name: 'Hebrew' },
  { code: 'hi-IN', name: 'Hindi' },
  { code: 'hu-HU', name: 'Hungarian' },
  { code: 'is-IS', name: 'Icelandic' },
  { code: 'id-ID', name: 'Indonesian' },
  { code: 'it-IT', name: 'Italian (Italy)' },
  { code: 'it-CH', name: 'Italian (Switzerland)' },
  { code: 'ja-JP', name: 'Japanese' },
  { code: 'jv-ID', name: 'Javanese' },
  { code: 'kn-IN', name: 'Kannada' },
  { code: 'kk-KZ', name: 'Kazakh' },
  { code: 'km-KH', name: 'Khmer' },
  { code: 'ko-KR', name: 'Korean' },
  { code: 'lo-LA', name: 'Lao' },
  { code: 'lv-LV', name: 'Latvian' },
  { code: 'lt-LT', name: 'Lithuanian' },
  { code: 'mk-MK', name: 'Macedonian' },
  { code: 'ms-MY', name: 'Malay' },
  { code: 'ml-IN', name: 'Malayalam' },
  { code: 'mr-IN', name: 'Marathi' },
  { code: 'mn-MN', name: 'Mongolian' },
  { code: 'ne-NP', name: 'Nepali' },
  { code: 'no-NO', name: 'Norwegian' },
  { code: 'fa-IR', name: 'Persian' },
  { code: 'pl-PL', name: 'Polish' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)' },
  { code: 'pa-Guru-IN', name: 'Punjabi' },
  { code: 'ro-RO', name: 'Romanian' },
  { code: 'ru-RU', name: 'Russian' },
  { code: 'sr-RS', name: 'Serbian' },
  { code: 'si-LK', name: 'Sinhala' },
  { code: 'sk-SK', name: 'Slovak' },
  { code: 'sl-SI', name: 'Slovenian' },
  { code: 'so-SO', name: 'Somali' },
  { code: 'es-AR', name: 'Spanish (Argentina)' },
  { code: 'es-BO', name: 'Spanish (Bolivia)' },
  { code: 'es-CL', name: 'Spanish (Chile)' },
  { code: 'es-CO', name: 'Spanish (Colombia)' },
  { code: 'es-CR', name: 'Spanish (Costa Rica)' },
  { code: 'es-DO', name: 'Spanish (Dominican Republic)' },
  { code: 'es-EC', name: 'Spanish (Ecuador)' },
  { code: 'es-SV', name: 'Spanish (El Salvador)' },
  { code: 'es-GT', name: 'Spanish (Guatemala)' },
  { code: 'es-HN', name: 'Spanish (Honduras)' },
  { code: 'es-MX', name: 'Spanish (Mexico)' },
  { code: 'es-NI', name: 'Spanish (Nicaragua)' },
  { code: 'es-PA', name: 'Spanish (Panama)' },
  { code: 'es-PY', name: 'Spanish (Paraguay)' },
  { code: 'es-PE', name: 'Spanish (Peru)' },
  { code: 'es-PR', name: 'Spanish (Puerto Rico)' },
  { code: 'es-ES', name: 'Spanish (Spain)' },
  { code: 'es-US', name: 'Spanish (United States)' },
  { code: 'es-UY', name: 'Spanish (Uruguay)' },
  { code: 'es-VE', name: 'Spanish (Venezuela)' },
  { code: 'su-ID', name: 'Sundanese' },
  { code: 'sw-KE', name: 'Swahili (Kenya)' },
  { code: 'sw-TZ', name: 'Swahili (Tanzania)' },
  { code: 'sv-SE', name: 'Swedish' },
  { code: 'ta-IN', name: 'Tamil (India)' },
  { code: 'ta-MY', name: 'Tamil (Malaysia)' },
  { code: 'ta-SG', name: 'Tamil (Singapore)' },
  { code: 'ta-LK', name: 'Tamil (Sri Lanka)' },
  { code: 'te-IN', name: 'Telugu' },
  { code: 'th-TH', name: 'Thai' },
  { code: 'tr-TR', name: 'Turkish' },
  { code: 'uk-UA', name: 'Ukrainian' },
  { code: 'ur-IN', name: 'Urdu (India)' },
  { code: 'ur-PK', name: 'Urdu (Pakistan)' },
  { code: 'uz-UZ', name: 'Uzbek' },
  { code: 'vi-VN', name: 'Vietnamese' },
  { code: 'cy-GB', name: 'Welsh' },
  { code: 'zu-ZA', name: 'Zulu' },
  
  // Additional languages to reach 189 total
  { code: 'ab-GE', name: 'Abkhazian' },
  { code: 'aa-DJ', name: 'Afar' },
  { code: 'ak-GH', name: 'Akan' },
  { code: 'sq-AL', name: 'Albanian' },
  { code: 'as-IN', name: 'Assamese' },
  { code: 'ay-BO', name: 'Aymara' },
  { code: 'ba-RU', name: 'Bashkir' },
  { code: 'be-BY', name: 'Belarusian' },
  { code: 'bh-IN', name: 'Bihari' },
  { code: 'bi-VU', name: 'Bislama' },
  { code: 'br-FR', name: 'Breton' },
  { code: 'dz-BT', name: 'Dzongkha' },
  { code: 'eo-XX', name: 'Esperanto' },
  { code: 'ee-GH', name: 'Ewe' },
  { code: 'fo-FO', name: 'Faroese' },
  { code: 'fj-FJ', name: 'Fijian' },
  { code: 'fy-NL', name: 'Frisian' },
  { code: 'ff-SN', name: 'Fulah' },
  { code: 'gd-GB', name: 'Gaelic (Scottish)' },
  { code: 'ga-IE', name: 'Irish' },
  { code: 'gn-PY', name: 'Guarani' },
  { code: 'ha-NG', name: 'Hausa' },
  { code: 'ho-PG', name: 'Hiri Motu' },
  { code: 'ig-NG', name: 'Igbo' },
  { code: 'ia-FR', name: 'Interlingua' },
  { code: 'ie-XX', name: 'Interlingue' },
  { code: 'iu-CA', name: 'Inuktitut' },
  { code: 'ik-US', name: 'Inupiaq' },
  { code: 'kg-CD', name: 'Kongo' },
  { code: 'kv-RU', name: 'Komi' },
  { code: 'ku-TR', name: 'Kurdish' },
  { code: 'ky-KG', name: 'Kyrgyz' },
  { code: 'ln-CD', name: 'Lingala' },
  { code: 'lu-CD', name: 'Luba-Katanga' },
  { code: 'lb-LU', name: 'Luxembourgish' },
  { code: 'mg-MG', name: 'Malagasy' },
  { code: 'mt-MT', name: 'Maltese' },
  { code: 'mi-NZ', name: 'Maori' },
  { code: 'mh-MH', name: 'Marshallese' },
  { code: 'mo-MD', name: 'Moldavian' },
  { code: 'na-NR', name: 'Nauru' },
  { code: 'nv-US', name: 'Navajo' },
  { code: 'nd-ZW', name: 'North Ndebele' },
  { code: 'nr-ZA', name: 'South Ndebele' },
  { code: 'ng-NA', name: 'Ndonga' },
  { code: 'ny-MW', name: 'Nyanja' },
  { code: 'oc-FR', name: 'Occitan' },
  { code: 'or-IN', name: 'Oriya' },
  { code: 'om-ET', name: 'Oromo' },
  { code: 'os-RU', name: 'Ossetian' },
  { code: 'pi-IN', name: 'Pali' },
  { code: 'ps-AF', name: 'Pashto' },
  { code: 'qu-PE', name: 'Quechua' },
  { code: 'rm-CH', name: 'Romansh' },
  { code: 'rn-BI', name: 'Rundi' },
  { code: 'sm-WS', name: 'Samoan' },
  { code: 'sg-CF', name: 'Sango' },
  { code: 'sa-IN', name: 'Sanskrit' },
  { code: 'sc-IT', name: 'Sardinian' },
  { code: 'sn-ZW', name: 'Shona' },
  { code: 'sd-PK', name: 'Sindhi' },
  { code: 'ss-SZ', name: 'Swati' },
  { code: 'st-LS', name: 'Southern Sotho' },
  { code: 'tn-BW', name: 'Tswana' },
  { code: 'to-TO', name: 'Tonga' },
  { code: 'ts-ZA', name: 'Tsonga' },
  { code: 'tk-TM', name: 'Turkmen' },
  { code: 'tw-GH', name: 'Twi' },
  { code: 'ug-CN', name: 'Uighur' },
  { code: 'vo-XX', name: 'Volapük' },
  { code: 'wa-BE', name: 'Walloon' },
  { code: 'wo-SN', name: 'Wolof' },
  { code: 'xh-ZA', name: 'Xhosa' },
  { code: 'yi-YD', name: 'Yiddish' },
  { code: 'yo-NG', name: 'Yoruba' },
  { code: 'za-CN', name: 'Zhuang' }
];

/**
 * Get a language by its code
 * @param code The language code to search for
 * @returns The language object or undefined if not found
 */
export const getLanguageByCode = (code: string) => {
  return supportedLanguages.find(lang => lang.code === code);
};

/**
 * Get a language by its name
 * @param name The language name to search for
 * @returns The language object or undefined if not found
 */
export const getLanguageByName = (name: string) => {
  return supportedLanguages.find(lang => lang.name.toLowerCase() === name.toLowerCase());
};

/**
 * Get all languages for a specific region/country
 * @param countryCode The country code (e.g., 'US', 'IN')
 * @returns Array of languages for the specified country
 */
export const getLanguagesByCountry = (countryCode: string) => {
  return supportedLanguages.filter(lang => {
    const parts = lang.code.split('-');
    return parts.length > 1 && parts[parts.length - 1] === countryCode;
  });
};

/**
 * Default language code to use when none is specified
 */
export const DEFAULT_LANGUAGE_CODE = 'en-US';

/**
 * Auto-detection language code
 */
export const AUTO_DETECTION_CODE = 'auto';
